version: "3.8"

services:
  # 🔹 MySQL Database Service
  mysql:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # ✅ Ensures DB & User Exist

  # 🔹 Backend API Service (Flask)
  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env  # ✅ Loads Environment Variables
    volumes:
      - ./backend:/app
    command: python3 app.py

volumes:
  mysql_data:
